name: MLflow Docker Integration
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mlflow:
        image: python:3.8-slim
        ports:
          - "5000:5000"
        env:
          MLFLOW_TRACKING_URI: "http://localhost:5000"
        volumes:
          - ./mlruns:/mlruns
        # Uses your Dockerfile setup
        run: |
          pip install mlflow numpy
          mlflow server \
            --host 0.0.0.0 \
            --backend-store-uri sqlite:///mlflow.db \
            --default-artifact-root ./artifacts
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Test connection
      run: |
        sleep 10  # Wait for MLflow
        curl http://localhost:5000
        python test_mlflow.py
