name: Medical Imaging Pipeline CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mlflow:
        image: mlflow/mlflow
        ports:
          - "5000:5000"
        env:
          MLFLOW_BACKEND_STORE_URI: "sqlite:////mlruns/mlflow.db"
          MLFLOW_DEFAULT_ARTIFACT_ROOT: "/mlartifacts"
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov nibabel  # Added nibabel for medical image support
    
    - name: Run MLflow connection test
      run: python test_mlflow.py
    
    - name: Run unit tests
      run: |
        python -m pytest tests/ --cov=./ --cov-report=xml
      env:
        MLFLOW_TRACKING_URI: "http://localhost:5000"
    
    - name: Upload coverage
      uses: codecov/codecov-action@v3

  docker-build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker images
      run: docker-compose build
    
    - name: Start services
      run: docker-compose up -d
      env:
        MLFLOW_TRACKING_URI: "http://localhost:5000"
    
    - name: Verify services
      run: |
        sleep 15  # Wait for services to start
        docker-compose ps
        curl -v http://localhost:5001/load_hyperk || echo "Service check failed but continuing"
