name: Medical Imaging Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mlflow:
        image: ghcr.io/mlflow/mlflow:latest
        ports:
          - "5000:5000"
        env:
          MLFLOW_BACKEND_STORE_URI: "sqlite:////mlruns/mlflow.db"
          MLFLOW_DEFAULT_ARTIFACT_ROOT: "/mlartifacts"
        options: --health-cmd "curl -f http://localhost:5000 || exit 1" --health-interval 10s
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest pytest-cov nibabel
    
    - name: Verify MLflow
      run: |
        sleep 10
        curl --retry 5 --retry-delay 3 --retry-all-errors http://localhost:5000
    
    - name: Run tests
      run: |
        python -m pytest tests/ --cov=./ --cov-report=xml
      env:
        MLFLOW_TRACKING_URI: "http://localhost:5000"
    
    - name: Upload coverage
      uses: codecov/codecov-action@v3

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: docker-compose build
    - run: docker images
